### ISSUE TITLE
Unset variables should error

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/gitsh#136]
`commit $foo`, when `$foo` is unset, should print an error message and not continue.

This is in `transformer.rb`, in the `:var` rule.

Currently it passes an empty string to `#spawn` as the last argument:

    ["/usr/bin/env", "git", "commit"@0, ""]

Ideally this should do something more predictable: either error, or pass the empty string (`"\"\""`). Calle and I vote: error.

**Comment by georgebrock** [comment]
I was wrong. Unset variables should be errors.
