### ISSUE TITLE
Tab completion doesn't work for file names containing parentheses

### ISSUE THREAD

**Issue by neilkimmett** [thoughtbot/gitsh#150]
Say I type in `diff MyCoolApp.xcodepr` and hit tab, I would expect it to be tab completed to `diff MyCoolApp.xcodeproj/` but it isn't :disappointed:

**Comment by georgebrock** [comment]
We're now using a custom GNU Readline integration, which means we should be able to fix this by:

* Making sure `(` and `)` in completions are escaped to `\(` and `\)`,
* exposing GNU Readline's `rl_char_is_quoted_p` setting (see https://github.com/georgebrock/readline-extensions for an example), and
* setting a `char_is_quoted` proc that recognises `\(` as a quoted `(`, etc.

The same approach will probably fix #189.

**Comment by neilkimmett** [comment]
Thats awesome news, thanks for following up on this @georgebrock. I didn't have this problem for a while but now that I work at Harry's I'm seeing the same issues with the apostrophe character in filenames. Let me know when theres something to play with and I'll be happy to help test it out.

**Comment by georgebrock** [comment]
Fixed by #259.
