### ISSUE TITLE
Support a `.gitshrc` file

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/gitsh#190]
This would be useful for creating settings and aliases that should only apply within gitsh.

Examples:

* I usually use Git through gitsh, unless I'm using a non-interactive script. For scripting purposes, colours can cause problems, but in an interactive gitsh session they're very useful. I could add `:set color.ui auto` to my `.gitshrc` file to enable colours in gitsh only.
* I have `tig` aliased to `!tig` in my `.gitconfig` file so I can easily invoke tig from within gitsh. I could move this alias to my `.gitshrc` file, since it's only useful from within gitsh.

**Comment by georgebrock** [comment]
It might make sense to do this by implementing a `:source` command, which could be used to load the `.gitshrc` file.

**Comment by mike-burns** [comment]
So I would have to type `:source` every time I start gitsh?

**Comment by georgebrock** [comment]
I was thinking gitsh would call `:source ~/.gitshrc` automatically, but if we implement `:source` first it'll make things nice and reusable.

**Comment by georgebrock** [comment]
Implemented `:source` in 595232da42a10b7161809cbd69b10bac597509ba, which involved some changes to the `Gitsh::ScriptRunner` to make it more easily reusable.

Thanks to this commit we can load the `~/.gitshrc` reasonably easily, either with the new `Gitsh::Commands::Internal::Source`, or just by directly invoking the `Gitsh::ScriptRunner`.

**Comment by georgebrock** [comment]
Closed in favour of PR #219
