### ISSUE TITLE
Replace mocha with RSpec mocks

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/gitsh#215]
RSpec now has the mocking features that were missing a year ago and caused me to select mocha. Other developers seem to be surprised that the project isn't using RSpec mocks. Let's use mocha to make it easier for other developers to get involved.

**Comment by teoljungberg** [comment]
@georgebrock I can gladly take a stab at this on friday, maybe pair up with someone else from the Stockholm office

**Comment by georgebrock** [comment]
@teoljungberg That would be great. Thanks, Teo.
