### ISSUE TITLE
Auto complete stash commands

### ISSUE THREAD

**Issue by lode** [thoughtbot/gitsh#220]
I miss auto completion for `stash` commands.

Mainly the stash names `stash@{0}` when typing `stash show -p` + tab I would like it to expand to `stash show -p stash@{` and to show me a list of stashes.

But also the main commands would be nice, like `stash a` + tab => `stash apply`.

Right now branch names and directories are auto completed and shown on multiple choices. I don't know about other people, but I hardly use those functionality with `stash`.

**Comment by georgebrock** [comment]
After the tab completion improvements introduced in #296, #304, #310, #311, #312, #313, we can now tab complete stash commands (and other popular commands with sub-commands!).
