### ISSUE TITLE
Branch Name Truncation

### ISSUE THREAD

**Issue by dougc84** [thoughtbot/gitsh#223]
I recently updated to gitsh 0.9, and am unhappy with the branch name truncation to 15 characters.  My team uses `git-flow` to manage our features, hotfixes, and releases.  Because of the way `git-flow` works, I'll often have a branch called `feature/net-5919-some-brief-description` (the `net-5919` is replaced with the key to the issue in our issue tracker).

This causes the prompt to display: `feature/net-591...`, which tells me nothing about where I'm at - I'm not even getting the full issue code.

Is there some configuration setting that can adjust this length?  I'm not aware of any .gitsh file configuration either.

**Comment by georgebrock** [comment]
There are various `git config` settings that can be used to configure gitsh, including `gitsh.prompt`. Before 0.9 the default was `%D %c%b%#%w`, in 0.9 we introduced the `%B` placeholder for a truncated branch name and switched the default from the full branch name (`%b`) to the truncated version (`%B`).

You can get the old default behaviour back with this command (from within gitsh):

```
config --global gitsh.prompt "%D %c%b%#%w"
```

If you want to customise the prompt further, you can read more about what the various `%` placeholders mean in the gitsh(1) manual page (`!man gitsh` from within gitsh).

**Comment by dougc84** [comment]
@georgebrock Awesome!  I was unaware of the `!man gitsh` command.  I'll look into it further.  Thanks for your help!
