### ISSUE TITLE
Thoughts on having a bare `cd` go to repo root

### ISSUE THREAD

**Issue by christoomey** [thoughtbot/gitsh#242]
Using `gitsh` this past week I ended up using the internal `:cd` command to move into a subfolder in my repo to do some work there, then wanted to return to the repo root (in the `gitsh` context).

I was only able to do this by knowing the correct count of `../`s to get back to the root.

I'd like to add support for `:cd` with no argument to chdir to the repo root (much like a bare `cd` in the shell going to `$HOME`). I began work on this but hit a few snags and wanted to see what the team thought.
### Specific questions I have are:
- Does this make sense? Specifically, is it logical to think of a `gitsh` instance existing within the context of a single repo? This is exclusively how I use it, but might not be the case.
- If this does makes sense, what is the best implementation? I see two main options:
  - Dynamically find the root when `:cd` is invoked (using `git rev-parse --show-cdup`)
  - Capture the repo root on gitsh startup and save in the `env`

I'm more than happy to work on this should it make sense, but wanted to get a quick sanity check before going further.

**Comment by georgebrock** [comment]
I think this makes a lot of sense, and I'd welcome this feature.

Another thing to consider might be a magic variable—something like `$_root`—that would evaluate to the root of the repository.

**Comment by mike-burns** [comment]
Re gitsh startup: it's possible to `:cd` into another repo, and I consider that a feature.

(And I do think a bare `:cd` should go to the repo root -- that makes sense to me.)

**Comment by christoomey** [comment]
I think my approach will be to detect the root dynamically at command run time with the `rev-parse` option.

If the user has `:cd`ed out of any repo, should that error or be a noop?

**Comment by mike-burns** [comment]
They might have `:cd`'ed into another directory in order to run `init`.

**Comment by christoomey** [comment]
Sorry, my question was worded poorly. I was referring to the case where someone had `:cd`ed out of any repo and then ran `:cd` with no argument. Should that error, or just noop? I lean towards noop, but could be convinced of providing and error message in that case.

**Comment by mike-burns** [comment]
I'd be happy with noop. I'll leave the decision up to George, though.

**Comment by georgebrock** [comment]
I think it should fail, in that it should return `false` behind the scenes so that `:cd && foo` wouldn't ever run `foo` outside of a Git repo. And if that's the case, it should probably output an error.

Does that seem reasonable?

**Comment by mike-burns** [comment]
Good thinking.

**Comment by christoomey** [comment]
I hadn't realized that the internal commands could be `&&`ed. With that in mind, I'm :+1: on @georgebrock's suggestion. Will implement with `false` and error message.

**Comment by georgebrock** [comment]
Closing in favour of #290
