### ISSUE TITLE
Switch the formula to SHA256

### ISSUE THREAD

**Issue by catalandres** [thoughtbot/gitsh#248]
The installation via `brew` throws the following error:

`Warning: SHA1 support is deprecated and will be removed in a future version.
Please switch this formula to SHA256.`

**Comment by georgebrock** [comment]
@catalandres Thanks for the heads up

**Comment by georgebrock** [comment]
This was fixed by hand on the v0.10 formula (https://github.com/thoughtbot/homebrew-formulae/pull/30) now that I'm prepping the v0.11 release, I've updated the release script to use SHA256 too (#275).
