### ISSUE TITLE
Support the same tab completion options as zsh

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/gitsh#25]
Completion in general is very lacking compared to ZSH, but I'm not sure we can anything about that.

**Comment by lode** [comment]
I have a similar experience coming from [git-sh](https://github.com/rtomayko/git-sh). It feels git-sh is smarter about the context of the command.

I personally don't feel comfortable enough with ruby to start implementation, but would love to help getting this further. Would it be a good start to list some specific situations? Or is the current references to zsh and git-sh enough? (Is this a good issue btw, or is there another more generic issue already?)

**Comment by mike-burns** [comment]
Specifics would be great, pull requests with failing tests would be even better, and pull requests with working code is most ideal.

See https://github.com/thoughtbot/gitsh/blob/master/CONTRIBUTING.md for details on how to get the dev environment running locally. Not too much Ruby knowledge is required for this (you'll need RubyGems and Bundler: `apt-get install rubygems bundler`). Make sure this runs and passes:

    make check

Edit `spec/units/completer_spec.rb` and copy one of the existing file path tests. Something like:

```ruby
it 'completes partial paths' do
  with_a_temporary_home_directory do
    completer = build_completer(input: 'add ')
    Dir.chdir do
      FileUtils.mkdir_p(%w(abc def ghi jkl mno))
    end

    expect(completer.call('a/d/g/j/m')).to include 'abc/def/ghi/jkl/mno'
  end
end
```

Then run the test according to CONTRIBUTING.md:

    env TESTS="spec/units/completer_spec" make -e check

If you want to tackle the Ruby after that, look in `lib/gitsh/completer.rb`, especially the `PathCompleter` class (line 102-ish). You'll need to modify the `#collection` method.

**Comment by lode** [comment]
Thanks for the push into actual coding :) I tried ruby a while back and noticed it costs me a lots of time for small things, so I'll save it for later. Or, at least I'll start with some specific things I'd like to see different. Maybe later or maybe someone else can pick some up.

Some auto completion (via tab) wishes:
- `push ` would give `push origin ` (ending space)
- `merge ori` would give `merge origin/` (ending slash)
- `stash pop ` would give `stash pop stash@{` (further auto completion lists the available numbers or even the output of `stash list`)
- in general auto complete branch names instead of paths where a branch name can be expected

Often the extra space or slash at the end makes all the difference between fluently continue typing or having to type redundant stuff.

**Comment by mike-burns** [comment]
Perhaps a DSL for expressing completions would be useful, such that we can express:

```
push $remote $branch
merge $branch
stash pop $stash
```

And `$remote` completes with a space at the end, `$branch` completes remotes with a slash at the end, and `$stash` completes from the stash list.

@georgebrock how's that for over-engineered?

**Comment by lode** [comment]
I'm not sure what exactly you mean with `$remote` and `$branch` but note that the ending char differs per command.

`push $remote $branch` has a space after `$remote`
`merge $remote/$branch` has a slash after `$remote`, unless you see that `origin/foobar` is a branch-name only?

**Comment by georgebrock** [comment]
@mike-burns That could be quite a nice way of expressing it.

@lode I'd see `origin/foobar` as a branch name, rather than an origin and a branch. Most commands that take a branch name work just as well with local branches and remote tracking branches.

**Comment by lode** [comment]
@georgebrock indeed, than it works perfectly of course.

**Comment by georgebrock** [comment]
After the tab completion improvements introduced in #296, #304, #310, #311, #312, #313, I think the tab completion is at least as good as the zsh completion that ships with Git, if not better. Thanks, @mike-burns, for the comment on this issue that inspired the DSL-based approach.

There are further specific improvements I'd like to make to tab completion, documented in #314, #315, #316, #317, #318, and #319.

Given the recent improvements, and all of those new more-specific issues, I'm going to close this.
