### ISSUE TITLE
Test suite issues on Ruby 2.2.2p95

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/gitsh#268]
Paired with George, making a note here:

On Ruby 2.2.2p95, the test suite becomes interactive. This is because `GetOpenFile` sets `ofp->fd` to `0`. We're not sure why; we tried on 2.3.1p112 and it works correctly.

Possible resolution for this issue is to be closed with an explanation that gitsh devs are expected to use something besides 2.2.2p95.

**Comment by georgebrock** [comment]
Now that Ruby 2.4 is out, and 2.2 is up to 2.2.7, it seems increasingly unlikely that new gitsh developers will try to run it on 2.2.2.

If anyone runs into this issue in future: you should use a newer version of Ruby for gitsh development.
