### ISSUE TITLE
Add HEAD support to brew formula (or release)

### ISSUE THREAD

**Issue by merrill-oakland** [thoughtbot/gitsh#271]
Please either add HEAD support to the formula (per https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md) or release more often.

Last release version was in Sept 2015 even though there has been plenty of git activity since then.

**Comment by georgebrock** [comment]
Thanks for the nudge. I've been working on the “or release” option today, and we're close. I'll close this when 0.11 ships.

**Comment by merrill-oakland** [comment]
Thanks.

Absolutely love gitsh - indispensable to my workflow for years now, so thank you very much!

**Comment by georgebrock** [comment]
And we're released!

https://github.com/thoughtbot/gitsh/releases/tag/v0.11
