### ISSUE TITLE
No prompt beyond initial message on how to exit the git shell

### ISSUE THREAD

**Issue by perrupa** [thoughtbot/gitsh#282]
![image](https://cloud.githubusercontent.com/assets/1577452/23473486/62997c72-fe7e-11e6-8a59-d21ad42af3b1.png)

If you don't know to call `:exit` (and miss the initial message), it's very difficult/poor ux to discover how to quit the gitsh. If possible, it would be nice to listen for `exit` or `quit` (possibly even `ctrl+c`) and exit, or simply remind the user that the command is `:exit`.

**Comment by georgebrock** [comment]
gitsh follows the convention of the vast majority of Unix shells here, and exits in response to EOF (<kbd><kbd>ctrl</kbd>+<kbd>d</kbd></kbd>). I'd recommend using that.
