### ISSUE TITLE
Cannot start, not find rltk

### ISSUE THREAD

**Issue by hongquan** [thoughtbot/gitsh#309]
I installed gitsh from Git. When I launch gitsh, it said error:

```
$ gitsh
/usr/local/share/gitsh/ruby/lib/gitsh/interpreter.rb:1:in `require': cannot load such file -- rltk (LoadError)
	from /usr/local/share/gitsh/ruby/lib/gitsh/interpreter.rb:1:in `<top (required)>'
	from /usr/local/share/gitsh/ruby/lib/gitsh/file_runner.rb:1:in `require'
	from /usr/local/share/gitsh/ruby/lib/gitsh/file_runner.rb:1:in `<top (required)>'
	from /usr/local/share/gitsh/ruby/lib/gitsh/input_strategies/interactive.rb:2:in `require'
	from /usr/local/share/gitsh/ruby/lib/gitsh/input_strategies/interactive.rb:2:in `<top (required)>'
	from /usr/local/share/gitsh/ruby/lib/gitsh/cli.rb:5:in `require'
	from /usr/local/share/gitsh/ruby/lib/gitsh/cli.rb:5:in `<top (required)>'
	from /usr/local/share/gitsh/ruby/gitsh.rb:6:in `require'
	from /usr/local/share/gitsh/ruby/gitsh.rb:6:in `<main>'
```

But my system already has `rltk`:

```
$ gem which 'rltk'                                                                                                      
/var/lib/gems/2.3.0/gems/rltk-3.0.1/lib/rltk.rb
```

**Comment by georgebrock** [comment]
Installing from Git is not recommended—you should follow the instructions in the `INSTALL` file instead: https://github.com/thoughtbot/gitsh/blob/master/INSTALL

If you really want to install from Git, you should follow the instructions in the contributing guide to build gitsh before running `make install`—it's possible you missed the `bundle` step in this process:
https://github.com/thoughtbot/gitsh/blob/master/CONTRIBUTING.md

**Comment by georgebrock** [comment]
To give more background on why this happens: gitsh installs its own copy of the RLTK gem (and any other gems in requires). This is because your tools shouldn't be dependent on things in your development environment—if you upgrade RLTK for a Ruby project you're working on, that shouldn't effect gitsh.

**Comment by hongquan** [comment]
Thanks. I now install from GitHub release tarball and it works.
