### ISSUE TITLE
Open from a different working directory

### ISSUE THREAD

**Issue by mxlang** [thoughtbot/gitsh#322]
First, thanks for this great tool! This is more of an enhancement request based on my gitsh usage.

In my workflow, I am working in a tmux session launched from my home directory, which opens in a project's root directory (which is not a git directory itself). The project contains a couple subdirs, each containing multiple git repositories. Currently, whenever I trigger the gitsh pane, it opens in the context of my home dir so I have to navigate to the project dir and to the git repos dir. I would very much enjoy if gitsh could open in the current pane's directory instead, making it easier to navigate to the git repos subdir.

I suggest adding a "-C workdir" option that would allow specifying a working directory. This would make it possible to configure the gitsh shortcut in tmux.conf so it opens in the current pane's directory.

Thanks again!

**Comment by gfontenot** [comment]
This seems out of scope for `gitsh` to me. That being said, I'm _pretty_ sure I have config that would do what you want via tmux: https://github.com/gfontenot/dotfiles/blob/master/tmux.conf#L28-L29

**Comment by mxlang** [comment]
I understand this could be seen as out of scope, however many utilities implements it and I personally find it very useful! I use this all the time instead of "cd" in and out...
That being said, your config does exactly what I was trying to achieve. It just shows I do not master my tmux config enough!
Many thanks!
