### ISSUE TITLE
"Which git" prompt placeholder

### ISSUE THREAD

**Issue by benknoble** [thoughtbot/gitsh#323]
My gitsh prompt contains the string `git` at the end of the prompt, both to remind me of my context and to let me know that everything is getting a git prefix.

```
project (feature-branch @) git> 
```
I get this with `%D (%c%b %#%w) git> `.

I have `hub` installed, and use it frequently, but typically *only* to interact with github (again, this is for context purposes). However, occasionally I want to fire up gitsh with hub (`gitsh --git "$(which hub)"`). Most often I do this in a split tmux pane via a hotkey.

I would like to be able to see the "git binary" being used in my prompt.

Would it be possible for gitsh to support a prompt placeholder that resolves to the currently-used git binary?

Something like
```
%g        basename of current git binary
%G        full name of current git binary
```

Then the prompt `%D (%c%b %#%w) %g> ` would become
- `project (feature-branch @) git> ` when run normally
- `project (feature-branch @) hub> ` when run with `hub`
- &c.

This extends to `gh` and other git providers (??) as well.

**Comment by georgebrock** [comment]
Great suggestion, thanks @benknoble.

This probably overlaps a bit with #231 too.

**Comment by benknoble** [comment]
Actually, in keeping with the current gitsh prompt strings, I think it makes sense to reverse the meaning of `%g` and `%G` mentioned above.

**Comment by benknoble** [comment]
Furthermore, were I to try to implement this, would it make sense to strip `usr/bin/env` from the "full path" to binary" and `env` from the basename?

Without stripping, we get things like

```
project (feature-branch @) /usr/bin/env git> 
project (feature-branch @) env git> 
```

when run normally, which I'm not a fan of, but I could see a use-case of something like `gitsh --git "/usr/bin/env hub"` (weird as it seems) where knowing that `env` was used might be important.
