### ISSUE TITLE
Is it possible for the process name to be "gitsh" instead of "ruby"?

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/gitsh#327]
I had a quick look into `Process.setproctitle`, which seems useful, but still doesn't affect `$0`, which I guess is what is shown by my terminal when running `gitsh`.

**Comment by georgebrock** [comment]
This is surprisingly complex, especially on macOS. 

This is covered by #41, and there's more discussion there, so I'm going to close this issue and keep that one open.
