### ISSUE TITLE
aclocal(1) not found on macOS

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/gitsh#339]
- macOS Mojave Version 10.14.2

Following [CONTRIBUTING.md](https://github.com/thoughtbot/gitsh/blob/9a903e128b83bbbf35ad6a9588ad6953360c0ecd/CONTRIBUTING.md), I ran `./autogen.sh` and got the following error:

```
% ./autogen.sh
./autogen.sh: line 3: aclocal: command not found
```

I had to `brew install automake` in order to proceed.

**Comment by georgebrock** [comment]
Thanks, @sharplet. I think I've addressed this in #341; I'll close this issue and we ca move any further conversation to that PR.
