### ISSUE TITLE
Tab completion for git-rebase

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/gitsh#349]
- macOS Mojave 10.14.3
- gitsh 0.13

When I type `rebase <tab>`, I get completions for branch names, as expected. When I type `rebase master <tab>`, no completions are offered.

**Comment by georgebrock** [comment]
Looks like a mistake in the [completion definition for rebase](https://github.com/thoughtbot/gitsh/blob/master/etc/completions#L649).

```
rebase $opt* $revision $anything
```

Instead of `$revision $anything` it would probably make more sense to use `$revision+`

**Comment by georgebrock** [comment]
Fixed in e0584c825b2e3c87b14db8aafb4db4f74af7d961
