### ISSUE TITLE
Fall back to path completion for external commands?

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/gitsh#362]
When I type `!ls <tab>`, it would be nice to get a list of paths as completion options. As of gitsh 0.14, this seems to be offering me git-themed completion options, which doesn't seem quite right unless I typed `!git <tab>`.

**Comment by georgebrock** [comment]
@sharplet Paths should also be available, the [v0.14 fallback configuration][1] is:

    fallback::$command $opt* ($revision|$path|$remote)* -- $path*

Looking at this a little more, if I type things like `!ls a<tab>` I do get path completions starting with `a`, and when I type `!ls <tab>` one of the options is `/`, so maybe there's a bug in how we're generating or filtering path completion options.

We should definitely fix that. I also wonder if we should add some common `!` commands to the fallback config, or even if we should have a catch-all that any external shell command only gets path arguments.

[1]: https://github.com/thoughtbot/gitsh/blob/v0.14/etc/completions#L925
