### ISSUE TITLE
Interactive rebase broken with hub

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/gitsh#375]
Reporting on behalf of @mxie, who mentioned this in passing:

When using [hub](https://github.com/github/hub) instead of git, interactive rebasing spews Perl error messages instead of performing the rebase.

And now here's @mxie with more details:

**Comment by mxie** [comment]
Thanks for opening this @mike-burns! It turns out that this is only happening to a very specific repo so I'm guessing that it has something to do with the dev setup. We can close this!
