### ISSUE TITLE
Custom key bindings/commands

### ISSUE THREAD

**Issue by jandamm** [thoughtbot/gitsh#378]
Hey there, 
nice project! I really enjoy using it.

Is there a way to change key bindings?
In particular I'd be interested in a different C-p/n command.

In my zsh shell I've mapped C-p to backwards history search. So pressing C-p after typing `a` would result in the last command starting with `a` instead of the previous command.
Is there something similar?
(I probably should train myself to use C-r anyways, but still 😉)

Cheers 
Jan

**Comment by georgebrock** [comment]
gitsh uses GNU Readline as its line editor, which can be configured with a `$HOME/.inputrc` file.

In your case, I think you might be looking for something like:

```
"\C-p": history-search-backward
"\C-n": history-search-forward
```

Note that settings in your `.inputrc` file will apply to all programs that use GNU Readline, which seems to be the majority of interactive shells (notable exceptions are zsh, which has its own line editor called ZLE; and any program compiled against libedit, which is theoretically compatible with Readline but only provides a subset of the features and is especially common on macOS).

If you want to make this configuration apply only in gitsh, you can wrap it in a conditional:

```
$if gitsh
    "\C-p": history-search-backward
    "\C-n": history-search-forward
$endif
```

See the [readline(3)](https://linux.die.net/man/3/readline) and gitsh(1) manual pages for more information.

**Comment by georgebrock** [comment]
Given that this is already supported, I'm going to close the issue, but feel free to re-open if you think there's some missing functionality here.

**Comment by jandamm** [comment]
Thanks for the help.
I've never really used bash and went straight to zsh (for my interactive shell) so I wasn't aware of inputrc.
Now I even got my vi keybindings 👌
