### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ThaDaVos** [thoughtbot/gitsh#386]
Like the title says `Is this project dead?` - there seems to be no commits since 2019...

**Comment by georgebrock** [comment]
It depends what you mean by “dead.”

It's a tool that a lot of people use every day and find useful, myself included.

There are features that I'd like to add, but nothing huge. If there's a specific feature that you think is missing, then pull requests are welcome.

**Comment by ThaDaVos** [comment]
I meant it in the way of almost no commits, lots of issues open without responses on them - just asking though
