### ISSUE TITLE
The process name should be `gitsh`, not `ruby`

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/gitsh#41]

**Comment by sharplet** [comment]
I'm starting to wonder whether it would be necessary to write a simple C program that spawns a ruby child process to run gitsh. I experimented with a bootstrap program that sets up an argument list and then calls `execve(2)`, but the exec is transparent in the same way, and the process still shows up as `ruby` — in which case, ruby might need to be launched using something like `posix_spawn(2)`.

It's not a tonne of code, but it's tricky and harder to maintain or contribute to. Uncertain if it's worth the complexity?

**Comment by georgebrock** [comment]
@sharplet The gitsh binary is already a small C program that spawns Ruby, see: https://github.com/thoughtbot/gitsh/commit/d7f97b360e6039baecd3a48b337a9c1ae99e269b

The original motivation for this was that some OSes don't allow an interpreted program (i.e. a program with a sh-bang line) to be used in another interpreted program's sh-bang line.

Since we already have that particular bit of complexity, making the program spawn Ruby differently isn't a huge jump.
