### ISSUE TITLE
Add tab completion for options

### ISSUE THREAD

**Issue by JoelQ** [thoughtbot/gitsh#80]
According to the README:

> Tab completion for git commands, aliases, and branches without modifying your shell settings, and without any extra setup for aliases and third party git commands.

Tab completion works for commands/branches but not for options. For example, if I want to run `rebase --continue` I can tab-complete the `rebase` but not the `--continue`. ZSH allowed me to complete both. It would be nice to add this ability to `gitsh`.

**Comment by georgebrock** [comment]
After the tab completion improvements introduced in #296, #304, #310, #311, #312, #313, we can now tab complete options!
