### ISSUE TITLE
Install problem on Ubuntu 13.10

### ISSUE THREAD

**Issue by lawrencem** [thoughtbot/gitsh#84]
I get an error from ./configure:

/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require': cannot load such file -- bundler (LoadError)
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
	from ./vendor/vendorize:3:in `<main>'
configure: error: Vendorizing gems failed

What do I need to do to fix this?

Thanks,
Lawrence

**Comment by georgebrock** [comment]
There's been no update on this for a while, and with the improved instructions I can't reproduce it. Closing.
