### ISSUE TITLE
exit vs :exit

### ISSUE THREAD

**Issue by shsteven** [thoughtbot/gitsh#93]
I have git auto corrections enabled.
Sometimes I forgot to type the colon in `:exit`, and git auto correction would misunderstand it as `init`.

Can `exit` be mapped to `:exit`?

    WARNING: You called a Git command named 'exit', which does not exist.
    Continuing under the assumption that you meant 'init'

**Comment by georgebrock** [comment]
Since shipping the welcome message and changing the README, there hasn't been any new demand for this. I'm still happy with not blurring the lines between gitsh commands and Git commands.

Closing for real this time.
